version: '3.9'

services:
  ros_noetic_nvidia:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
    container_name: ros-noetic-dev-nvidia
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./../src:/home/dev/ros_ws/src
    networks:
      - ros_network
    command: "sleep infinity"
    privileged: true
    entrypoint: "/entrypoint.sh"
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"

networks:
  ros_network:
    driver: bridge
