version: '3.9'

services:
  ros_noetic_headless:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nvidia
    container_name: ros-noetic-dev-headless
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    volumes:
      # Mounts ssh credentials from host
      - /home/$USER/.ssh:/home/dev/.ssh
      # Mounts src directory within a ros workspace
      - ./../src:/home/dev/ros_ws/src
    networks:
      - ros_network
    command: "sleep infinity"
    privileged: true
    entrypoint: "/entrypoint.sh"

networks:
  ros_network:
    driver: bridge
